- name: install tomcat 
  hosts: all
  become: true
  tasks:
    - name: Download file and force basic auth for tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz
        dest: /home/ec2-user/
        force_basic_auth: yes
    - name: Extract apache-tomcat.tgz into /home/ec2-user
      unarchive:
        src: /home/ec2-user/apache-tomcat-8.5.99.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Download template file
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page296/listrace.zip
        dest: /opt/apache-tomcat-8.5.99/webapps/
        force_basic_auth: yes
    - name: Extract listrace.zip into /opt/apache-tomcat-8.5.99/webapps/
      unarchive:
        src: /opt/apache-tomcat-8.5.99/webapps/listrace.zip
        dest: /opt/apache-tomcat-8.5.99/webapps/
        remote_src: yes
    - name: install java
      yum:
       name: java
       state: present

    - name: This command will change the working directory to somedir/.
      shell:
        cmd: bash /opt/apache-tomcat-8.5.99/bin/startup.sh start
